### ISSUE TITLE
Execution failed for task ':app:processDebugResources'. > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade    > Android resource linking failed      D:\Flutter\dicee-flutter-v2\android\app\src\main\res\values\styles.xml:4:5-8:13: AAPT: error: resource drawable/launch_background (aka com.example.dicee_flutter_v2:drawable/launch_background) not found.

### ISSUE THREAD

**Issue by araraya** [mattkoch614/dicee-flutter-v2#1]
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\Flutter\dicee-flutter-v2\android\app\src\main\res\values\styles.xml:4:5-8:13: AAPT: error: resource drawable/launch_background (aka com.example.dicee_flutter_v2:drawable/launch_background) not found.

help, I don't know what to do

**Comment by mattkoch614** [comment]
@araraya Can you be more specific about the steps taken to arrive at this error message?

**Comment by aryaseek** [comment]
Sorry for late respond, this massage trow an error when I tried to view project to android, maybe some graddle file is missing. I fix it with create new flutter project. Thank you
